### ISSUE TITLE
Two checkboxes?

### ISSUE THREAD

**Issue by lsolesen** [vih/sport_2014#6]
Why are there two checkboxes after switching to Radix and Bootstrap 3? https://vih.dk/formular/kontakt

**Comment by shadcn** [comment]
Is this the latest Radix? We fixed that in the latest one. See https://www.drupal.org/node/2339395#comment-9311381

**Comment by lsolesen** [comment]
From https://github.com/vih/vih-build/blob/7.x-1.x/drupal-org.make

```
projects[radix][version] = 3.0-beta2
```

And Gemfile https://github.com/vih/sport_2014/blob/7.x-3.x/Gemfile

```
gem 'compass', '>= 0.12.2'
gem 'bootstrap-sass', '>= 3.0.3.0'
gem 'compass_radix', '>= 3.0.1'
```

**Comment by lsolesen** [comment]
Hm, seems that the Gemfile has come out of sync with the Radix Gemfile in my theme. Reinstalling right now.

**Comment by lsolesen** [comment]
Hm, still the same after https://github.com/vih/sport_2014/commit/939304b97f43ecfb2f8e6c28800afe32ded34d58

**Comment by shadcn** [comment]
I tried to reproduce this with the latest Radix but it is rendering only 1 checkbox.

See http://note.io/1wFvHQP

Anything I'm doing wrong?
